- name: News
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: calendar
          first-day-of-week: monday

    - size: full
      widgets:
        - type: group
          widgets:
            - type: rss
              limit: 50
              collapse-after: 15
              cache: 12h
              feeds:
              - url: https://www.rts.ch/info/?format=rss/news
                title: RTS Info
              - url: http://newsrss.bbc.co.uk/rss/newsonline_uk_edition/world/rss.xml
                title: BBC News — World

              - url: https://rss.dw.com/rdf/rss-en-world
                title: DW — World

              - url: https://www.theguardian.com/world/rss
                title: The Guardian — World

    - size: small
      widgets:
        - type: weather
          location: Bern, Switzerland
          units: metric # alternatively "imperial"
          hour-format: 12h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          # hide-location: true
