services:
  glance:
    container_name: glance-dev
    image: glanceapp/glance:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
    # If you want to enable the Docker containers widget, uncomment below
    # - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
